services:
  stats-server:
      build: ./stats-service/stats-server
      image: stats-server
      container_name: stats-server
      ports:
        - "9090:9090"
      depends_on:
        - ewm-service
      environment:
        - SPRING_DATASOURCE_USERNAME=stats
          - SPRING_DATASOURCE_PASSWORD=stats
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
        - SHAREIT_SERVER_URL=http://ewm-service:8080
        - TZ=Europe/Moscow

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - POSTGRES_DB=stats




