services:
  stats-server:
      build: ./stats-service/stats-server
      image: stats-server
      container_name: stats-server
      ports:
        - "9090:9090"
      depends_on:
        - ewm-service
      environment:
        - SPRING_DATASOURCE_USERNAME=stats
          - SPRING_DATASOURCE_PASSWORD=stats
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:6541/stats
        - SHAREIT_SERVER_URL=http://ewm-service:8080
        - TZ=Europe/Moscow

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - POSTGRES_DB=stats

  ewm-service:
    ports:
      - "8080:8080"
    build: ./main-service
    image: main-server
    container_name: main-server
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:7070/users
      - SHAREIT_SERVER_URL=http://stat-server:9090
      - TZ=Europe/Moscow



  ewm-db:
      image: postgres:16.1
      container_name: postgres-ewm-main-db
      ports:
        - "7070:7070"
      environment:
        - POSTGRES_USER=ewm
        - POSTGRES_PASSWORD=ewm
        - POSTGRES_DB=ewm





